2020-11-10 22:52:25.807924: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-11-10 22:52:25.918066: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-11-10 22:52:25.918614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Quadro P5000 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:0b:00.0
totalMemory: 15.90GiB freeMemory: 15.36GiB
2020-11-10 22:52:25.918636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-11-10 22:52:26.219048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-10 22:52:26.219090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-11-10 22:52:26.219097: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-11-10 22:52:26.219204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14877 MB memory) -> physical GPU (device: 0, name: Quadro P5000, pci bus id: 0000:0b:00.0, compute capability: 6.1)
class_weights {0: 7.528996865203761, 1: 0.5355669528375515}
X_train shape: (9607, 1, 32, 231)
X_testshape: (4806, 1, 32, 231)
9607 train samples
4806 test samples
chans: 32 samples: 231
Train on 9607 samples, validate on 4802 samples
Epoch 1/1000

Epoch 00001: val_loss improved from inf to 0.25135, saving model to /tmp/checkpoint.h5
 - 36s - loss: 0.2555 - acc: 0.9333 - val_loss: 0.2514 - val_acc: 0.9336
Epoch 2/1000

Epoch 00002: val_loss improved from 0.25135 to 0.24982, saving model to /tmp/checkpoint.h5
 - 35s - loss: 0.2500 - acc: 0.9336 - val_loss: 0.2498 - val_acc: 0.9336
Epoch 3/1000

Epoch 00003: val_loss improved from 0.24982 to 0.24539, saving model to /tmp/checkpoint.h5
 - 35s - loss: 0.2482 - acc: 0.9336 - val_loss: 0.2454 - val_acc: 0.9336
Epoch 4/1000

Epoch 00004: val_loss improved from 0.24539 to 0.24513, saving model to /tmp/checkpoint.h5
 - 35s - loss: 0.2481 - acc: 0.9336 - val_loss: 0.2451 - val_acc: 0.9336
Epoch 5/1000

Epoch 00005: val_loss improved from 0.24513 to 0.24278, saving model to /tmp/checkpoint.h5
 - 35s - loss: 0.2473 - acc: 0.9336 - val_loss: 0.2428 - val_acc: 0.9336
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

Bad key "text.kerning_factor" on line 4 in
/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
Epoch 6/1000
Traceback (most recent call last):
  File "MyERP.py", line 198, in <module>
    callbacks=[checkpointer], class_weight = class_weights)
  File "/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 215, in fit_loop
    outs = f(ins_batch)
  File "/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "/home/wtsmith/anaconda3/envs/arl/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
KeyboardInterrupt
